"""CLI entrypoint for the UNICAL scraping pipeline."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import click

from .extract.buildings import crawl_buildings
from .extract.departments import crawl_departments
from .extract.services import crawl_services
from .extract.teachers import crawl_teachers
from .transform.normalize import (
    normalize_buildings,
    normalize_departments,
    normalize_services,
    normalize_teachers,
    write_json,
)
from .utils.html_cache import HtmlCache
from .utils.http import DEFAULT_USER_AGENT, HttpClient
from .validate.integrity import check_integrity, issues_to_dicts
from .validate.jsonschema_validate import validate_dataset_dir
from .validate.report import build_coverage_report


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DATA_DIR = REPO_ROOT / "data" / "normalized"
DEFAULT_SCHEMAS_DIR = REPO_ROOT / "data" / "schema"


def _load_json_array(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []

    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)

    if not isinstance(payload, list):
        return []
    return [item for item in payload if isinstance(item, dict)]


def _upsert_source_entry(sources_file: Path, source_entry: dict[str, str]) -> None:
    existing = _load_json_array(sources_file)
    by_id: dict[str, dict[str, Any]] = {
        str(item["source_id"]): item for item in existing if item.get("source_id")
    }
    by_id[source_entry["source_id"]] = source_entry
    sorted_entries = sorted(by_id.values(), key=lambda item: str(item["source_id"]))
    write_json(sources_file, sorted_entries)


@click.group()
def cli() -> None:
    """UNICAL data extraction, normalization, and validation CLI."""


@cli.group()
def crawl() -> None:
    """Extract data from UNICAL public sources."""


@crawl.command("teachers")
@click.option(
    "--base-url",
    default="https://www.unical.it/storage/teachers/",
    show_default=True,
    help="Entry URL used to discover teacher pages.",
)
@click.option(
    "--out-file",
    default=str(DEFAULT_DATA_DIR / "people.json"),
    show_default=True,
    type=click.Path(path_type=Path),
    help="Path where normalized people dataset will be written.",
)
@click.option(
    "--cache-dir",
    default=None,
    type=click.Path(path_type=Path),
    help="Optional cache dir for HTML snapshots.",
)
@click.option("--rate-limit", default=0.5, show_default=True, type=float)
@click.option("--user-agent", default=DEFAULT_USER_AGENT, show_default=True)
def crawl_teachers_command(
    base_url: str,
    out_file: Path,
    cache_dir: Path | None,
    rate_limit: float,
    user_agent: str,
) -> None:
    """Crawl professor pages and write normalized `people.json`."""
    cache = HtmlCache(cache_dir) if cache_dir else None

    with HttpClient(user_agent=user_agent, rate_limit_seconds=rate_limit) as client:
        raw_teachers = crawl_teachers(base_url=base_url, client=client, cache=cache)

    people = normalize_teachers(raw_teachers)
    write_json(out_file, people)

    sources_file = out_file.parent / "sources.json"
    source_entry = {
        "source_id": "unical-teachers",
        "name": "UNICAL Teachers Directory",
        "base_url": base_url,
        "notes": "Generated by unical_scraper crawl teachers",
        "last_crawled_at": datetime.now(timezone.utc).isoformat(),
    }
    _upsert_source_entry(sources_file=sources_file, source_entry=source_entry)

    click.echo(f"Crawled {len(raw_teachers)} teachers")
    click.echo(f"Wrote: {out_file}")
    click.echo(f"Wrote: {sources_file}")


@crawl.command("departments")
@click.option(
    "--base-url",
    default="https://www.unical.it/ateneo/dipartimenti",
    show_default=True,
    help="Departments page URL.",
)
@click.option(
    "--out-file",
    default=str(DEFAULT_DATA_DIR / "departments.json"),
    show_default=True,
    type=click.Path(path_type=Path),
    help="Path where normalized departments dataset will be written.",
)
@click.option(
    "--cache-dir",
    default=None,
    type=click.Path(path_type=Path),
    help="Optional cache dir for HTML snapshots.",
)
@click.option("--rate-limit", default=0.5, show_default=True, type=float)
@click.option("--user-agent", default=DEFAULT_USER_AGENT, show_default=True)
def crawl_departments_command(
    base_url: str,
    out_file: Path,
    cache_dir: Path | None,
    rate_limit: float,
    user_agent: str,
) -> None:
    """Crawl department pages and write normalized `departments.json`."""
    cache = HtmlCache(cache_dir) if cache_dir else None

    with HttpClient(user_agent=user_agent, rate_limit_seconds=rate_limit) as client:
        raw_departments = crawl_departments(base_url=base_url, client=client, cache=cache)

    departments = normalize_departments(raw_departments)
    write_json(out_file, departments)

    sources_file = out_file.parent / "sources.json"
    source_entry = {
        "source_id": "unical-departments",
        "name": "UNICAL Departments",
        "base_url": base_url,
        "notes": "Generated by unical_scraper crawl departments",
        "last_crawled_at": datetime.now(timezone.utc).isoformat(),
    }
    _upsert_source_entry(sources_file=sources_file, source_entry=source_entry)

    click.echo(f"Crawled {len(raw_departments)} departments")
    click.echo(f"Wrote: {out_file}")
    click.echo(f"Wrote: {sources_file}")


@crawl.command("services")
@click.option(
    "--base-url",
    required=True,
    help="Services page URL.",
)
@click.option(
    "--out-file",
    default=str(DEFAULT_DATA_DIR / "places.json"),
    show_default=True,
    type=click.Path(path_type=Path),
    help="Path where normalized places dataset will be written.",
)
@click.option(
    "--cache-dir",
    default=None,
    type=click.Path(path_type=Path),
    help="Optional cache dir for HTML snapshots.",
)
@click.option("--rate-limit", default=0.5, show_default=True, type=float)
@click.option("--user-agent", default=DEFAULT_USER_AGENT, show_default=True)
def crawl_services_command(
    base_url: str,
    out_file: Path,
    cache_dir: Path | None,
    rate_limit: float,
    user_agent: str,
) -> None:
    """Crawl service pages and write normalized `places.json`."""
    cache = HtmlCache(cache_dir) if cache_dir else None

    with HttpClient(user_agent=user_agent, rate_limit_seconds=rate_limit) as client:
        raw_services = crawl_services(base_url=base_url, client=client, cache=cache)

    places = normalize_services(raw_services)
    write_json(out_file, places)

    sources_file = out_file.parent / "sources.json"
    source_entry = {
        "source_id": "unical-services",
        "name": "UNICAL Services",
        "base_url": base_url,
        "notes": "Generated by unical_scraper crawl services",
        "last_crawled_at": datetime.now(timezone.utc).isoformat(),
    }
    _upsert_source_entry(sources_file=sources_file, source_entry=source_entry)

    click.echo(f"Crawled {len(raw_services)} services")
    click.echo(f"Wrote: {out_file}")
    click.echo(f"Wrote: {sources_file}")


@crawl.command("buildings")
@click.option(
    "--base-url",
    default="https://www.unical.it/campus/visita-il-campus/mappa/",
    show_default=True,
    help="Campus map page URL.",
)
@click.option(
    "--out-file",
    default=str(DEFAULT_DATA_DIR / "buildings.json"),
    show_default=True,
    type=click.Path(path_type=Path),
    help="Path where normalized buildings dataset will be written.",
)
@click.option(
    "--cache-dir",
    default=None,
    type=click.Path(path_type=Path),
    help="Optional cache dir for HTML snapshots.",
)
@click.option("--rate-limit", default=0.5, show_default=True, type=float)
@click.option("--user-agent", default=DEFAULT_USER_AGENT, show_default=True)
def crawl_buildings_command(
    base_url: str,
    out_file: Path,
    cache_dir: Path | None,
    rate_limit: float,
    user_agent: str,
) -> None:
    """Crawl campus buildings and write normalized `buildings.json`."""
    cache = HtmlCache(cache_dir) if cache_dir else None

    with HttpClient(user_agent=user_agent, rate_limit_seconds=rate_limit) as client:
        raw_buildings = crawl_buildings(base_url=base_url, client=client, cache=cache)

    buildings = normalize_buildings(raw_buildings)
    write_json(out_file, buildings)

    sources_file = out_file.parent / "sources.json"
    source_entry = {
        "source_id": "unical-campus-map",
        "name": "UNICAL Campus Map",
        "base_url": base_url,
        "notes": "Generated by unical_scraper crawl buildings",
        "last_crawled_at": datetime.now(timezone.utc).isoformat(),
    }
    _upsert_source_entry(sources_file=sources_file, source_entry=source_entry)

    click.echo(f"Crawled {len(raw_buildings)} buildings")
    click.echo(f"Wrote: {out_file}")
    click.echo(f"Wrote: {sources_file}")


@cli.command("validate")
@click.option(
    "--data-dir",
    default=str(DEFAULT_DATA_DIR),
    show_default=True,
    type=click.Path(path_type=Path),
)
@click.option(
    "--schemas-dir",
    default=str(DEFAULT_SCHEMAS_DIR),
    show_default=True,
    type=click.Path(path_type=Path),
)
@click.option("--verbose", is_flag=True, help="Print individual validation issues.")
def validate_command(data_dir: Path, schemas_dir: Path, verbose: bool) -> None:
    """Validate JSON datasets against schema and referential integrity."""
    schema_results = validate_dataset_dir(data_dir=data_dir, schemas_dir=schemas_dir)
    integrity_issues = check_integrity(data_dir=data_dir)

    invalid_schema_files = 0
    for dataset_name, errors in schema_results.items():
        status = "OK" if not errors else "INVALID"
        click.echo(f"[{status}] {dataset_name}")
        if errors:
            invalid_schema_files += 1
            if verbose:
                for error in errors:
                    click.echo(f"  - {error}")

    if integrity_issues:
        click.echo("[INTEGRITY] Issues found")
        for issue in integrity_issues:
            click.echo(f"  - ({issue.level}) {issue.file}: {issue.message}")
    else:
        click.echo("[INTEGRITY] OK")

    error_integrity_count = sum(1 for issue in integrity_issues if issue.level == "error")
    if invalid_schema_files > 0 or error_integrity_count > 0:
        raise SystemExit(1)


@cli.command("report")
@click.option(
    "--data-dir",
    default=str(DEFAULT_DATA_DIR),
    show_default=True,
    type=click.Path(path_type=Path),
)
@click.option(
    "--schemas-dir",
    default=str(DEFAULT_SCHEMAS_DIR),
    show_default=True,
    type=click.Path(path_type=Path),
)
@click.option(
    "--out",
    default=str(DEFAULT_DATA_DIR / "report.json"),
    show_default=True,
    type=click.Path(path_type=Path),
)
def report_command(data_dir: Path, schemas_dir: Path, out: Path) -> None:
    """Build a deterministic coverage + validation report JSON."""
    schema_results = validate_dataset_dir(data_dir=data_dir, schemas_dir=schemas_dir)
    integrity_issues = check_integrity(data_dir=data_dir)

    report_payload = build_coverage_report(
        data_dir=data_dir,
        schema_results=schema_results,
        integrity_issues=issues_to_dicts(integrity_issues),
    )
    write_json(out, report_payload)
    click.echo(f"Wrote report: {out}")
